/**
 * Cross-language parity: the Node crypto must match the Python service exactly.
 *
 * Both services run against the same MongoDB during the cutover, so a hash
 * written by one must verify in the other. This file asserts that against
 * **fixtures generated by the Python code**, not against Node's own output —
 * a test that only checks Node against Node would pass happily while every
 * existing customer was locked out.
 *
 * Regenerate the fixtures from the Python repo with:
 *
 *   python -c "from app.security import hash_password, hash_email_otp; \
 *              print(hash_password('supersecret1')); print(hash_email_otp('123456'))"
 *
 * (`hash_email_otp` depends on JWT_SECRET, so use the same secret set below.)
 */
export {}; // Marks this file a module, so top-level `await` below is allowed.

// Guard first: the suites drop their database, and MONGODB_URI comes from
// .env, which may point at production.
await import('./local-only.js');

// Set before importing, because `getSettings()` reads the environment once and
// caches it — a later assignment would be ignored and the OTP vectors would be
// hashed under the wrong key.
process.env['JWT_SECRET'] = 'parity-test-secret';

const { hashEmailOtp, hashPassword, verifyPassword, hashApiKey, hashToken } = await import(
  '../src/security.js'
);

let passed = 0;
let failed = 0;

function check(name: string, condition: boolean, detail = ''): void {
  if (condition) {
    passed += 1;
    console.log(`  PASS  ${name}`);
  } else {
    failed += 1;
    console.log(`  FAIL  ${name}${detail ? `  ${detail}` : ''}`);
  }
}

console.log('\nCross-language parity with the Python service\n');

// --- Passwords --------------------------------------------------------------
// A REAL hash, produced by the Python service's hash_password("supersecret1").
// This is the test that matters: if Node cannot verify it, every existing
// customer is locked out the moment this service takes traffic.
const PYTHON_HASH =
  'pbkdf2_sha256$240000$d3c1c2eb018d13e5b86f5311b4378d62$' +
  '6bd2b430a009e443ac5e1fe75f7c2e1c33a1db03173a64f6b24626f9aaccd607';

check(
  'a password hashed by PYTHON verifies here',
  await verifyPassword('supersecret1', PYTHON_HASH),
);
check(
  'and the wrong password against the Python hash is refused',
  !(await verifyPassword('supersecret2', PYTHON_HASH)),
);

// A hash this code produces must verify in this code (round trip)...
const roundTrip = await hashPassword('supersecret1');
check('a hash we produce verifies here', await verifyPassword('supersecret1', roundTrip));
check('and refuses the wrong password', !(await verifyPassword('wrong', roundTrip)));

// ...and must be in exactly the format Python's verify_password() parses.
const parts = roundTrip.split('$');
check('our hash uses the shared format', parts.length === 4, roundTrip.slice(0, 30));
check('algorithm label matches', parts[0] === 'pbkdf2_sha256', String(parts[0]));
check('iteration count matches Python', parts[1] === '240000', String(parts[1]));
check('salt is 16 bytes of hex', (parts[2] ?? '').length === 32, String(parts[2]?.length));
check('digest is 32 bytes of hex', (parts[3] ?? '').length === 64, String(parts[3]?.length));

// Malformed input must be refused rather than throwing into a request handler.
check('an empty stored hash is refused', !(await verifyPassword('x', '')));
check('a truncated stored hash is refused', !(await verifyPassword('x', 'pbkdf2_sha256$240000')));
check(
  'an unknown algorithm is refused',
  !(await verifyPassword('x', 'bcrypt$12$aaaa$bbbb')),
);

// --- OTP hashing ------------------------------------------------------------
// HMAC-SHA256(JWT_SECRET, code), hex. This vector was produced by the Python
// service under JWT_SECRET='parity-test-secret'. A code issued by one service
// must be checkable by the other, or an OTP sent before the cutover fails after
// it — while the customer is holding the SMS.
const PYTHON_OTP_HASH = '2fdea173700e40893ab73ab7e8b462b043a1554a1e8b95b449121e23c571b58e';

const otpHash = hashEmailOtp('123456');
check('an OTP hashed by PYTHON matches ours', otpHash === PYTHON_OTP_HASH, otpHash);
check('an OTP hash is 64 hex chars', /^[0-9a-f]{64}$/.test(otpHash), otpHash);
check('the same code hashes the same way twice', otpHash === hashEmailOtp('123456'));
check('a different code hashes differently', otpHash !== hashEmailOtp('123457'));
// Keyed, not a bare digest: a plain sha256 of "123456" is this well-known value,
// and if we ever produced it, six-digit codes would be reversible from a dump.
check(
  'the OTP hash is keyed, not a bare SHA-256',
  otpHash !== '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',
);

// --- Opaque tokens ----------------------------------------------------------
// Plain SHA-256 hex, matching Python's hash_token / hash_api_key.
check(
  'token hashing matches SHA-256 of the UTF-8 bytes',
  hashToken('abc') === 'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad',
  hashToken('abc'),
);
check('api key hashing uses the same function', hashApiKey('abc') === hashToken('abc'));

console.log(`\n${passed} passed, ${failed} failed\n`);
if (failed > 0) process.exit(1);
