export {}; // Marks this file a module, so top-level `await` below is allowed.

/**
 * Schema parity: the documents Node writes must match the ones Python writes.
 *
 * This test exists because the port got it wrong. An earlier `credits.ts`
 * invented a `Decimal128` field called `balance`, while the Python service
 * stores integer minor units in `balance_units`. It passed every functional
 * test — because those tests only ever compared Node against Node — and would
 * have produced accounts the Python service read as having a zero balance, on a
 * shared production database.
 *
 * So this compares against **fixtures generated by the Python code**. Regenerate
 * them from the Python repo with `test/fixtures/dump_schema.py`.
 *
 * A key that Node writes and Python does not is a warning; a key Python writes
 * and Node does not is a failure — that is the direction in which data goes
 * missing.
 */
process.env['ENVIRONMENT'] = 'development';
process.env['JWT_SECRET'] = 'schema-parity-secret';
process.env['MONGODB_DB'] = 'chatbucket_b2b_nodetest';
process.env['SMS_BACKEND'] = 'memory';
process.env['EMAIL_BACKEND'] = 'memory';

import { readFileSync } from 'node:fs';
import { ObjectId } from 'mongodb';

const { connect, disconnect, creditAccountsCollection, creditLedgerCollection } = await import(
  '../src/database.js'
);
const credits = await import('../src/services/credits.js');

interface Fixture {
  credit_accounts: string[];
  credit_ledger: string[];
  users: string[];
  phone_verifications: string[];
}

const fixtures: Fixture = JSON.parse(
  readFileSync(new URL('./fixtures/python-schema.json', import.meta.url), 'utf8'),
);

let passed = 0;
let failed = 0;

function check(name: string, condition: boolean, detail = ''): void {
  if (condition) {
    passed += 1;
    console.log(`  PASS  ${name}`);
  } else {
    failed += 1;
    console.log(`  FAIL  ${name}${detail ? `  ${detail}` : ''}`);
  }
}

/** Every key Python writes must be present in what Node writes. */
function comparesTo(actual: Record<string, unknown>, expected: string[], label: string): void {
  const have = new Set(Object.keys(actual));
  const missing = expected.filter((k) => !have.has(k));
  const extra = [...have].filter((k) => !expected.includes(k) && k !== '_id');

  check(`${label}: writes every field Python writes`, missing.length === 0, `missing: ${missing}`);
  if (extra.length > 0) {
    console.log(`  NOTE  ${label}: extra fields Python does not write: ${extra.join(', ')}`);
  }
}

console.log('\nSchema parity with the Python service\n');

await connect();
const userId = new ObjectId();

try {
  await creditAccountsCollection().deleteMany({ user_id: userId });
  await creditLedgerCollection().deleteMany({ user_id: userId });

  // --- credit_accounts ------------------------------------------------------
  const account = await credits.getAccount(userId);
  comparesTo(account, fixtures.credit_accounts, 'credit_accounts');
  check(
    'the balance field is the integer one Python reads',
    typeof account['balance_units'] === 'number',
    `got ${typeof account['balance_units']}`,
  );
  check(
    'and there is no invented Decimal128 balance field',
    !('balance' in account),
    JSON.stringify(Object.keys(account)),
  );

  // --- credit_ledger --------------------------------------------------------
  await credits.grant(userId, credits.toUnits('100'), credits.KIND_SIGNUP_BONUS, 'Welcome credits');
  const entry = await creditLedgerCollection().findOne({ user_id: userId });
  comparesTo(entry ?? {}, fixtures.credit_ledger, 'credit_ledger');

  // --- Unit conversion ------------------------------------------------------
  // 1 credit = 10,000 units. Getting this wrong by a factor of 100 is the kind
  // of error that reads fine in a test and bills wrong in production.
  check('100 credits is 1,000,000 units', credits.toUnits('100') === 1_000_000);
  check('1 credit is 10,000 units', credits.toUnits('1') === 10_000);
  check('0.0001 credits is 1 unit', credits.toUnits('0.0001') === 1);
  check(
    'units round-trip exactly',
    credits.fromUnits(credits.toUnits('5.2')).toString() === '5.2',
    credits.fromUnits(credits.toUnits('5.2')).toString(),
  );
  check(
    'the granted balance reads back as 100 credits',
    (await credits.balanceOf(userId)).toString() === '100',
    (await credits.balanceOf(userId)).toString(),
  );

  // --- The overspend guard --------------------------------------------------
  const spent = await credits.tryDebit(userId, credits.toUnits('40'), 'test spend');
  check('a debit within balance succeeds', spent !== null);
  check(
    'and leaves the right balance',
    (await credits.balanceOf(userId)).toString() === '60',
    (await credits.balanceOf(userId)).toString(),
  );
  const overspend = await credits.tryDebit(userId, credits.toUnits('1000'), 'too much');
  check('a debit beyond balance is refused', overspend === null);
  check(
    'and did not move the balance',
    (await credits.balanceOf(userId)).toString() === '60',
    (await credits.balanceOf(userId)).toString(),
  );
} finally {
  await creditAccountsCollection().deleteMany({ user_id: userId });
  await creditLedgerCollection().deleteMany({ user_id: userId });
  await disconnect();
}

console.log(`\n${passed} passed, ${failed} failed\n`);
if (failed > 0) process.exit(1);
